version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "10:00"
  open-pull-requests-limit: 20
  reviewers:
  - dustinsgoodman
  labels:
  - dependency
